global using System;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Util.Data.EntityFrameworkCore;
global using Util.Platform.Domain.Models;
global using Util.Platform.Data.EntityTypeConfigurations.Identity;
